# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
apt_packages:
   - vsearch
bioc_packages:
   - DECIPHER
   - dada2
   - Biostrings
   - ShortRead
   - phyloseq
after_success:
  - Rscript -e 'covr::codecov()'
