# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_packages:
   - DECIPHER
   - Biostrings
   - ShortRead
after_success:
  - Rscript -e 'covr::codecov()'
